name: chaput
description: "Chaput App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # navigation
  go_router: ^14.2.0

  # network
  dio: ^5.7.0

  # local storage (tokens)
  flutter_secure_storage: ^9.2.2

  # json
  json_annotation: ^4.9.0

  # utils
  freezed_annotation: ^2.4.4
  uuid: ^4.5.1
  file_picker: ^10.2.0

  # media
  video_player: ^2.8.6

  # math
  vector_math: ^2.1.4

  three_js: ^0.2.7

  share_plus: ^12.0.1
  image_picker: ^1.2.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/tree_models/
    - assets/tree_models/three/
    - assets/videos/chaput_bg.M4V
    - assets/videos/chaput_bg_2.mp4
    - assets/images/
    - assets/images/tree_bg.png
    - assets/images/chaput_logo_256px_h.png
    - assets/images/chaput_tying_lady.png
    - assets/images/avatar_assets/
    - assets/images/avatar_assets/background/
    - assets/images/avatar_assets/male/
    - assets/images/avatar_assets/female/
    - assets/i18n/en.json
    - assets/i18n/tr.json
    - assets/i18n/de.json
    - assets/i18n/fr.json

  fonts:
    - family: Qanelas
      fonts:
        - asset: assets/fonts/QanelasThin.otf
          weight: 100
        - asset: assets/fonts/QanelasThinItalic.otf
          weight: 100
          style: italic

        - asset: assets/fonts/QanelasUltraLight.otf
          weight: 200
        - asset: assets/fonts/QanelasUltraLightItalic.otf
          weight: 200
          style: italic

        - asset: assets/fonts/QanelasLight.otf
          weight: 300
        - asset: assets/fonts/QanelasLightItalic.otf
          weight: 300
          style: italic

        - asset: assets/fonts/QanelasRegular.otf
          weight: 400
        - asset: assets/fonts/QanelasRegularItalic.otf
          weight: 400
          style: italic

        - asset: assets/fonts/QanelasMedium.otf
          weight: 500
        - asset: assets/fonts/QanelasMediumItalic.otf
          weight: 500
          style: italic

        - asset: assets/fonts/QanelasBold.otf
          weight: 700
        - asset: assets/fonts/QanelasBoldItalic.otf
          weight: 700
          style: italic

        - asset: assets/fonts/QanelasExtraBold.otf
          weight: 800
        - asset: assets/fonts/QanelasExtraBoldItalic.otf
          weight: 800
          style: italic

        - asset: assets/fonts/QanelasHeavy.otf
          weight: 900
        - asset: assets/fonts/QanelasHeavyItalic.otf
          weight: 900
          style: italic

        - asset: assets/fonts/QanelasBlack.otf
          weight: 900
        - asset: assets/fonts/QanelasBlackItalic.otf
          weight: 900
          style: italic
